### PR TITLE
RedrawInterval in config + typecasts

### PR DESCRIPTION
**Pull request by netcrns**
Adressing #19 and added typecasts, just in case (due to compiler warnings).

### CODE REVIEW

**Comment by netcrns** [comment]
For the docs:
Add a new line to ntop.conf with the keyword RedrawInterval and the default value 1000. Maybe add `# Intervals` as a category.

**Comment by gsass1** [comment]
Thanks!

**Comment by evandrocoan** [comment]
How to use this setting?

**Comment by evandrocoan** [comment]
I see there is a settings file: https://github.com/gsass1/NTop/blob/master/ntop.conf

Where is its default location? I could not find one in my home directory.

**Comment by mailinglists35** [comment]
@netcrns how do we use this? I see no doc no help arg no hotkey?

edit: found it in conf file

**Comment by mailinglists35** [comment]
> I see there is a settings file: https://github.com/gsass1/NTop/blob/master/ntop.conf
> 
> Where is its default location? I could not find one in my home directory.

i don't know where it should be but I created one in c:\bin where I keep all my standalone little utilities along with ntop.exe and it works

**Comment by netcrns** [comment]
@evandrocoan @mailinglists35 
hey sry i didn't respond earlier, i was lost in the fog
ntop looks for a config in the binary's directory

see: https://github.com/gsass1/NTop/blob/326ccd80b41842868f4247d1e8978e854658a710/ntop.c#L169-L214

**Comment by mailinglists35** [comment]
> hey sry i didn't respond earlier

no worries, github issues are the right place for async conversations ;-)

**Pull request merged**
